### ISSUE TITLE
Infraestrutura de hospedagem, backup e monitoração

### ISSUE THREAD

**Issue by julio010101** [labhackercd/wikilegis#106]
Prezados,
estou tentando implementar o WikiLegis na minha empresa, contudo estou sentido falta de um "guia de hospedagem", contendo respostas a algumas perguntas, tais como: 1) Qual a política de backup recomendada? 2) É necessário backup do redis? 3) O que deve ser monitorado? Apenas a URL? 4) Qual a recomendação para alta disponibilidade?
Desculpem se são perguntas muitos básicas.
At.te
Julio

**Comment by erivanio** [comment]
Bom dia Julio,
atualmente nós disponibilizamos o wikilegis como uma ferramenta do e-Democracia, através deste [repositório](https://github.com/labhackercd/edemocracia-colab), nele usamos o docker para fazer o deploy das aplicações, no docker-compose.yml basta selecionar as ferramentas que você deseja como no caso o do wikilegis "WIKILEGIS_ENABLED: True". Agora respondendo os questionamentos:
1. Nossas aplicações estão hospedadas em servidores da Câmara dos Deputados, aqui eles fazem um backup de todas as máquinas virtuais diariamente.
2. O wikilegis não utiliza o redis.
3. Se a pergunta foi sobre monitoramento de acesso nós utilizamos o google analytics em todas as páginas.
4. Nossa arquiterua, como não temos apenas o wikilegis, usamos 3 máquinas, uma para as aplicações, uma para o redis(utilizado no Discourse-Expressão e Audiências Interativas) e outra pro postgresql. Recentemente fizemos um upgrade na máquina das aplicações, porém para o wikilegis sempre utilizamos as mais básicas, um centos7, dual core com 16gb de ram.

**Comment by julio010101** [comment]
Prezado, muito obrigado pela pronta resposta, estava pensando mesmo nessa solução de "backup diário da VM", ótimo. Me ajudou muito.

Atenciosamente,
Julio
