### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by Judaxx** [labhackercd/wikilegis#120]
So I've been trying to get the project to be in portuguese for a few days now and I for as much as I've seen, you guys seem to use transifex to translate (based on locale, which I dont need).

Is there a simple way to make everything in portuguese without using transifex?

**Comment by cfviotti** [comment]
Wikilegis is already translated into portuguese but its english strings must be compiled first. 
Have you tried running `wikilegis/manage.py compilemessages`?

Also, we are not currently using Transifex for translating as its integration into the project was deemed unnecessary at the time.

**Comment by Judaxx** [comment]
Hey, that worked :)
My bad on opening an issue on a thing that is probably stated on the readme and I missed.

Also, I'd like to point out that when you get a fresh clone of the repo, the normalize.css is missing.

Anyway, thank you.

**Comment by cfviotti** [comment]
No problem!
Thanks for pointing out, we'll take a look.
