### ISSUE TITLE
Erro 500 ao registrar conta no Wikilegis

### ISSUE THREAD

**Issue by adfeno** [labhackercd/wikilegis#30]
# Passos para reproduzir

1. Tente criar uma conta no Wikilegis.
    * Talvez ajude se você tentar com um endereço de e-mail de um serviço diferente de Hotmail Yahoo, Bol, Uol, Terra, e Gmail. *E.g.*: Posteo.de, OpenMailBox.org, RiseUp.net.
    * Você também pode testar senhas muito fortes como: W!Ca8Fe!3No (mistura de: **Ca**rlos **Fe**lipe **No**gueira, 83, e **W!**kileg**!**s).

# Comportamento

Ao terminar de preencher os campos e tentar criar a conta, o usuário é levado para uma página que mostra o erro de número 500 (não me recordo qual o nome do erro, apenas o número).

# Outros efeitos

* Após criar a conta, tente criá-la novamente, e o servidor dirá que ela já existe.
* Tente entrar com a conta criada e o servidor dirá que ela está inativa.

# Notas

## Motivos de criação da conta (ativismo em prol do software livre)

* Decidi criar uma conta no Wikilegis pois quero propor uma alteração no PL 3684/2004 que discorre **justamente** sobre o movimento político filosófico do *software* livre, ao qual estudo desde 2011. [Eis o tópico na lista de discussão do Projeto Software Livre Brasil](topico-lista-psl-brasil). Participem!

[topico-lista-psl-brasil]: http://listas.softwarelivre.org/pipermail/psl-brasil/2016-May/005093.html

**Comment by adfeno** [comment]
Não se preocupem, nós todos sabemos que, assim como **qualquer criação do ser humano**, um software livre nem sempre é perfeito, nem sempre é amigável, nem sempre é seguro. Mas, se tem uma coisa que ele nunca mente sobre si mesmo, e que nós ativistas não devemos esquecer de educar: é a priorização das liberdades essenciais da sociedade.

Ao contrário dos ativistas do software livre, os proponentes do \[código-\]fonte aberto costumam mentir sobre a **possibilidade** de seus programas apresentarem defeitos, e além de tentarem apelar aos valores do consumidor, esquecem de educar a sociedade sobre suas liberdades essenciais.

**Comment by erivanio** [comment]
Obrigado pela contribuição! Realmente houve uma falha ao setar as variáveis do servidor de email, já foi resolvido.  :)

**Comment by adfeno** [comment]
Obrigado!

(Desculpe pela demora em responder, eu não sabia que eu tinha que fechar o relatório)
