### ISSUE TITLE
ola?  Podemos usar as issues?  

### ISSUE THREAD

**Issue by ppKrauss** [labhackercd/wikilegis#4]
Qual a politica de uso aqui para as `git/issues`? 
Só relatórios de bugs e sugestões de novas funcionalidades, ou vale também um pouco de perguntas-e-respostas sobre o software e sua comunidade de desenvolvedores?

**Comment by ravishi** [comment]
Olá. Não temos nenhuma política definida ainda, então todo o tipo de contribuição é bem-vinda! Acredito que com o tempo iremos criando políticas conforme for necessário.

**Comment by ppKrauss** [comment]
Reparei, depois de resolver problemas #5, que as pendencias do Wikilegis vinham sendo organizadas em https://trello.com/b/b4hyvcH2/wikilegis ... Que tal migrarmos tudo para cá, em issues? Posso ajudar.

O ambiente é mais robusto, e acolhedor para o "colaborador de software" (não sei quanto a outros tipos de colaboração).

**Comment by ravishi** [comment]
Então, nossa decisão de manter a discussão no Trello foi tomada justamente visando facilitar a inclusão de colaboradores "não-de-TI". Não que isso exclua as colaborações feitas "por aqui". Todo tipo de contribuição é bem-vinda!
