### ISSUE TITLE
problemas ao instalar em Debian Stable

### ISSUE THREAD

**Issue by ppKrauss** [labhackercd/wikilegis#5]
Seguindo os procedimentos recomendados no README, sem `sudo`  e com user comum... "warning: no previously-included files matching"... e estranho pedir `win32`... ambos antes do problema de permissão,
<pre>
git clone https://github.com/labhackercd/wikilegis.git
Cloning into 'wikilegis'...
remote: Counting objects: 381, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 381 (delta 66), reused 37 (delta 37), pack-reused 271
Receiving objects: 100% (381/381), 253.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (200/200), done.
Checking connectivity... done.

user@localhost:~/tests$ cd wikilegis

user@localhost:~/tests/wikilegis$ pip install -r requirements.txt
Downloading/unpacking Django==1.8.4 (from -r requirements.txt (line 1))
  Downloading Django-1.8.4-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
Downloading/unpacking django-admin-sortable2==0.5.2 (from -r requirements.txt (line 2))
  Downloading django-admin-sortable2-0.5.2.tar.gz (45kB): 45kB downloaded
  Running setup.py (path:/tmp/pip-build-mL8Zes/django-admin-sortable2/setup.py) egg_info for package django-admin-sortable2
    
    warning: no previously-included files matching '*.pyc' found under directory '*'
Downloading/unpacking django-appconf==1.0.1 (from -r requirements.txt (line 3))
  Downloading django_appconf-1.0.1-py2.py3-none-any.whl
Downloading/unpacking django-compressor==1.5 (from -r requirements.txt (line 4))
  Downloading django_compressor-1.5-py2.py3-none-any.whl (129kB): 129kB downloaded
Downloading/unpacking django-debug-toolbar==1.3.2 (from -r requirements.txt (line 5))
  Downloading django_debug_toolbar-1.3.2-py2.py3-none-any.whl (206kB): 206kB downloaded
Downloading/unpacking django-libsass==0.4 (from -r requirements.txt (line 6))
  Downloading django_libsass-0.4-py2-none-any.whl
Downloading/unpacking futures==3.0.3 (from -r requirements.txt (line 7))
  Downloading futures-3.0.3-py2-none-any.whl
Downloading/unpacking libsass==0.8.3 (from -r requirements.txt (line 8))
  Downloading libsass-0.8.3.tar.gz (229kB): 229kB downloaded
  Running setup.py (path:/tmp/pip-build-mL8Zes/libsass/setup.py) egg_info for package libsass
    
    warning: no files found matching 'win32/*.h'
Downloading/unpacking six==1.9.0 (from -r requirements.txt (line 9))
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking sqlparse (from django-debug-toolbar==1.3.2->-r requirements.txt (line 5))
  Downloading sqlparse-0.1.16.tar.gz (58kB): 58kB downloaded
  Running setup.py (path:/tmp/pip-build-mL8Zes/sqlparse/setup.py) egg_info for package sqlparse
    
Installing collected packages: Django, django-admin-sortable2, django-appconf, django-compressor, django-debug-toolbar, django-libsass, futures, libsass, six, sqlparse
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/django'

Storing debug log for failure in /home/peter/.pip/pip.log
user@localhost:~/tests/wikilegis$ 
</pre>

**Comment by ravishi** [comment]
@ppKrauss, o `pip` está tentando instalar os pacotes num diretório do sistema, onde você não tem permissão para escrever. Uma alternativa seria utilizar o `sudo`. Uma alternativa melhor ainda seria criar e ativar um `virtualenv` [1] antes de executar o `pip`.

[1] https://virtualenv.pypa.io/en/latest/

**Comment by ppKrauss** [comment]
Tentarei primeiro a segunda ideia... Já usei *virtualenv* antes em outra instalação, deve estar tudo instalado... Quais seriam exatamente as linhas de comando? Ex.
```
virtualenv env
. env/bin/activate
```
(em qual pasta?  o que rodar  depois?)

**Comment by ppKrauss** [comment]
Bom, usei `sudo`, os warnings iniciais foram os mesmos, mas em seguida resolveu o django, e demorou mais instalando supostamente mais coisas... Repetiu centenas de vezes o warning 
```
aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./libsass -I/usr/include/python2.7 -c libsass/lexer.cpp -o build/temp.linux-x86_64-2.7/libsass/lexer.o -c -O3 -fPIC -std=c++0x -Wall -Wno-parentheses
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-
```
...  Reclamou diversos "deprecated conversion" do gcc... Até que por fim terminou sem avisos aparentemente mais graves,
```
    changing mode of build/scripts-2.7/sassc.py from 644 to 755
    
    warning: no files found matching 'win32/*.h'
    changing mode of /usr/local/bin/sassc.py to 755
    Installing sassc script to /usr/local/bin
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for sqlparse
    changing mode of build/scripts-2.7/sqlformat from 644 to 755
    
    changing mode of /usr/local/bin/sqlformat to 755
Successfully installed Django django-admin-sortable2 django-appconf django-compressor django-debug-toolbar django-libsass futures libsass six sqlparse
Cleaning up...
```

Promto (!).  E agora, como faço para testar se deu certo?  em qual porta estaria rodando a aplicação? (nesse ponto vale a pena o README dizer algo mais ;-)

**Comment by ravishi** [comment]
Há um ótimo tutorial aqui: http://docs.python-guide.org/en/latest/dev/virtualenvs/.

Quanto aos warnings que apareceram durante a instalação, eles são normais, não há com o que se preocupar.

A porta em que a aplicação está rodando é informada na saída do comando `$ ./manage.py runserver`.

**Comment by ppKrauss** [comment]
@ravishi obrigado (!), está rodando algo no meu http://127.0.0.1:8000/ !

Bom, ainda não foi o que esperavamos, pois não via nada de wikilegis, é só uma página de administração do django... No console havia:
```
./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

September 21, 2015 - 09:03:20
Django version 1.8.4, using settings 'wikilegis.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

Rodei `python manage.py migrate` conforme solicitado. Agora tudo perfeito no console, mas continuo sem saber onde foi parar a *wikilegis*: a evolução é que aparece o logo com um link, mas nada do site navegar. Tem alguma sugestão de URL localhost para eu testar?

**Comment by ravishi** [comment]
@ppKrauss, demos uma incrementada no README para tentar esclarecer estes pontos.

**Comment by ppKrauss** [comment]
README melhorou (!), agora avança 1 página ;-)
Falta explicar como quem acabou de instalar vai saber user e senha ... Não tem como navegar em outras paginas sem saber user e senha.
