### ISSUE TITLE
problem with the newsletter

### ISSUE THREAD

**Issue by torresfabian** [labhackercd/wikilegis#91]
Thanks for sending me the new version of wikilegis. They really are doing a great job.

There is only one question that I have not been able to solve, it is the operation of the newslleter. I have checked and tested the mail data and despite everything being ok I did not get the newslleter I sent mail. Should I configure something at the cron level or execute a specific command?

Thank you for taking your time to answer me.

**Comment by msfernandes** [comment]
Hey @torresfabian ! Thanks fo use Wikilegis and help us to improve!
Yes, you have to create a cronjob to run `python manage.py newsletter_notification --periodicity <periodicity>`
`periodicity` value can be `daily` or `weekly`, so we recommend to set two cronjobs for which periodicity.

Cheers

**Comment by msfernandes** [comment]
Let me know if you solved your problem :)
